// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_T-4beO6q7jkcyyytcNCxv0QHZbnz8OQ',
    appId: '1:867146042969:web:d9e52bde151c894a246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    authDomain: 'diccon-evo.firebaseapp.com',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
    measurementId: 'G-YLJQRQBRRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoVhDnefLm1ql2-LY2GFCel0iA5KBb5SI',
    appId: '1:867146042969:android:3a71841159418ebf246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRT6Ys7EvXoCDFc1obebbAwUXi4oBjJkk',
    appId: '1:867146042969:ios:b3c422a1cd151660246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
    androidClientId: '867146042969-dljr3iq5q2udfklrfoucv63oimin9jbd.apps.googleusercontent.com',
    iosClientId: '867146042969-4qtid0s8vu9gbpccsmhq6hpipm9eakmp.apps.googleusercontent.com',
    iosBundleId: 'com.zeroboy.dicconEvo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRT6Ys7EvXoCDFc1obebbAwUXi4oBjJkk',
    appId: '1:867146042969:ios:b3c422a1cd151660246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
    androidClientId: '867146042969-dljr3iq5q2udfklrfoucv63oimin9jbd.apps.googleusercontent.com',
    iosClientId: '867146042969-4qtid0s8vu9gbpccsmhq6hpipm9eakmp.apps.googleusercontent.com',
    iosBundleId: 'com.zeroboy.dicconEvo',
  );
}
